//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_21_Company_selfservice_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awards
    {
        public string Award_ID { get; set; }
        public string Award_Name { get; set; }
        public string Description { get; set; }
        public string Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
