//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_21_Company_selfservice_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Awards = new HashSet<Awards>();
            this.Device = new HashSet<Device>();
            this.Medical_Insurance = new HashSet<Medical_Insurance>();
            this.Parking = new HashSet<Parking>();
            this.Payroll = new HashSet<Payroll>();
            this.Pension_Account = new HashSet<Pension_Account>();
            this.Timesheet = new HashSet<Timesheet>();
            this.User = new HashSet<User>();
            this.KT_Documents = new HashSet<KT_Documents>();
            this.Skillset = new HashSet<Skillset>();
        }
    
        public string Employee_ID { get; set; }
        public string Employee_First_Name { get; set; }
        public string Employee_Last_Name { get; set; }
        public string Designation_ID { get; set; }
        public string Company_Email { get; set; }
        public string Company_Phone { get; set; }
        public string Employee_Start_Date { get; set; }
        public string Mode_ID { get; set; }
        public string Project_ID { get; set; }
        public string Role_ID { get; set; }
        public string MealPlan_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awards> Awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
        public virtual Meal_Plan Meal_Plan { get; set; }
        public virtual Project Project { get; set; }
        public virtual Role Role { get; set; }
        public virtual Work_Mode Work_Mode { get; set; }
        public virtual Leaves Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Insurance> Medical_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parking> Parking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pension_Account> Pension_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheet> Timesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KT_Documents> KT_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skillset> Skillset { get; set; }
    }
}
