//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_21_Company_selfservice_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pension_Account
    {
        public string Pension_Account_ID { get; set; }
        public string Holder_Name { get; set; }
        public string Nominees { get; set; }
        public string employee { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
