//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_21_Company_selfservice_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repository
    {
        public string Repository_ID { get; set; }
        public string Storage_Available { get; set; }
        public string Department { get; set; }
    
        public virtual Department Department1 { get; set; }
    }
}
