//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_21_Company_selfservice_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public string Timesheet_ID { get; set; }
        public string Total_Working_Hours_Per_Month { get; set; }
        public string Week_Number { get; set; }
        public string employee { get; set; }
        public string leave { get; set; }
        public string payroll { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Leaves Leaves { get; set; }
        public virtual Payroll Payroll1 { get; set; }
    }
}
